.\" Copyright (c) 2014 Tristan Le Guern <tleguern@bouledef.eu>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\" The following requests are required for all man pages.
.\"
.Dd $Mdocdate: August 19 2014 $
.Dt GRAVATARHASH 1
.Os
.Sh NAME
.Nm gravatarhash
.Nd Generate an avatar URL from an email address
.Sh SYNOPSIS
.Nm
.Op Fl fs
.Op Fl d Cm default
.Op Fl h Cm md5 | Cm sha256
.Op Fl p Cm dns | Cm gravatar | Cm libravatar
.Ar email
.Sh DESCRIPTION
The
.Nm
utility processes the given
.Ar email
address into an URL pointing to an avatar image.
.Pp
Three providers are currently supported:
.Bl -bullet -compact
.It
Gravatar (https://secure.gravatar.com/);
.It
Libreavatar (https://www.libravatar.org/);
.It
self hosted people (SRV DNS query).
.El
The default is to do a DNS query first and fallback to Gravatar if the
query fails.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Specify what to do if the avatar doesn't exist.  Can be 404, mm, blank,
retro or absolutely anything.
.It Fl f
Enable the forcedefault flag.
.It Fl h
Use either
.Xr md5
or
.Xr sha256
for the hash creation.
.It Fl p
Only use the specified avatar provider.
.It Fl s
Use the HTTPS URL instead of the default one.
.El
.Sh SEE ALSO
.Xr md5 1
