#!/bin/sh
#
# Copyright (c) 2014 Tristan Le Guern <tleguern@bouledef.eu>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

set -e

readonly PROGNAME="`basename $0`"
readonly VERSION='v1.0'

usage() {
        echo "usage: $PROGNAME [-dhsV] email"
}

version() {
        echo "$PROGNAME $VERSION"
}

uri="http://www.gravatar.com"
tail="?d=retro"

while getopts ":dhsV" opt;do
	case $opt in
		d) set -x;;
		h) usage; exit 0;;	# NOTREACHED
		s) uri="https://secure.gravatar.com";;
		V) version; exit 0;;	# NOTREACHED
		:) echo "$PROGNAME: option requires an argument -- $OPTARG";
		   usage; exit 1;;	# NOTREACHED
		?) echo "$PROGNAME: unkown option -- $OPTARG";
		   usage; exit 1;;	# NOTREACHED
		*) usage; exit 1;;	# NOTREACHED
	esac
done
shift $(( $OPTIND -1 ))

if [ -z "$1" ]; then
	echo "$PROGNAME: email address expected"
	usage
	exit 1
else
	email="$1"
	shift
fi

if [ $# -ge 1 ]; then
	echo "$PROGNAME: invalid trailing chars -- $@"
	usage
	exit 1
fi

set -u

email="`echo $email|tr '[A-Z' '[a-z]'`"
if which md5 > /dev/null; then
       hash="`md5 -qs $email`"
else
       hash="`echo -n $email|md5sum|cut -d' ' -f1`"
fi

echo $uri/avatar/$hash$tail
