.\" Copyright (c) 2014 Tristan Le Guern <tleguern@bouledef.eu>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.\" The following requests are required for all man pages.
.\"
.Dd $Mdocdate$
.Dt GRAVATARHASH 1
.Os
.Sh NAME
.Nm gravatarhash
.Nd Generate a gravatar URL from an email address
.Sh SYNOPSIS
.Nm
.Op Fl dhsV
.Ar email
.Sh DESCRIPTION
The
.Nm
utility process the given
.Ar email
address into a full Gravatar URL.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl d
Enable debug mode.
.It Fl h
Print usage and quit.
.It Fl s
Use the HTTPS URL instead of the default one.
.It Fl V
Print version and quit.
.El
.Sh SEE ALSO
.Xr md5 1
